### PR TITLE
add net.logstash.log4j2.JSONEventLayoutV1 for log4j2 support

### PR DESCRIPTION
**Pull request by michaelkuechler**
- moved HostData to new package as it seemed misplaced with the new log4j2 package

### CODE REVIEW

**Comment by AndreasKl** [comment]
+1

**Comment by vsnguyen** [comment]
I noticed when using this.  You'd loose the logging level because its always an empty map.

```
{"@timestamp":"2015-11-18T15:08:24.843Z","source_host":"CKSCLP008.local","level":{},.....}
```

**Comment by maartenbosteels** [comment]
Hi Michael,

Thanks for this !
I think I found an issue in your code: the log-level doesn't end up in my log-files: the key is present but the value is always an empty object,  like this  "level":{}

I tried to reproduce this with your unit tests (net.logstash.log4j2.JSONEventLayoutV1Test)
but it seem that these tests are actually using the log4j 1.x appender and layout.

Are you actively using your patch ?
Or did you find another solution ?

**Comment by michaelkuechler** [comment]
> Are you actively using your patch?

I was to, but then priorities shifted :neutral_face: - so I guess one has to look at the issue sometime…

**Comment by maartenbosteels** [comment]
I fixed the issue with the log-level and discovered that your unit tests were using the log4j 1.x code.
So I removed the log4j 1.x code and fixed the unit tests as well 
=> https://github.com/DNSBelgium/log4j-jsonevent-layout

**Comment by callumcodes** [comment]
Will this PR be actioned and released anytime soon? The DNSBelgium fork appears to work.

**Comment by cmpsoares91** [comment]
Hello,
Are these changes planned to be merged anytime soon?
Kind regards

**Comment by michaelkuechler** [comment]
@cmpsoares91 as i wrote above: this is more than stale and AFAIR i never even ended up really using the code. so i consider this stale and probably outdated…

**Pull request closed without merging**
