### PR TITLE
Renaming JSONEventLayout classes to lineup with number versions

### PR DESCRIPTION
**Pull request by Spredzy**
Main `JSONEventLayout` classes have been renamed the following way
- JSONEventLayout -> JSONEventLayoutV0
- JSONEventLayoutV1 -> JSONEventLayout

### CODE REVIEW

**Comment by joekiller** [comment]
Why not have JSONEventLayoutV1 still exist as well?  That would help anyone that already implemented it with V1 layout.

**Comment by lusis** [comment]
I keep looking back at this change and I think I'd rather just commit to using version named classes and not have a `JSONEventLayout` at all. This makes it much easier to reason about for end users as opposed to a moving target for `JSONEventLayout` tracking the most current.

**Comment by electrical** [comment]
I have to agree with @lusis on this. its much clearer if to have a version for the schema.

**Comment by lusis** [comment]
I've gone ahead and went the route I mentioned. This will kick in with 1.6 release (dfbdfcdcd9a4a4e95fbb6efcf396e68b5be28626)

**Pull request closed without merging**
