### PR TITLE
Use the reference implementation of JSR-353

### PR DESCRIPTION
**Pull request by datenbrille**
JSR-353 (http://jcp.org/en/jsr/detail?id=353) has his final draft. Oracle provides an reference implementation that will be used in upcomming JEE7 specification.

I replaced net.minidev.json with the RI and removed the commons lang dependency. It will give the encoder a lower footprint.

Additional I removed the Hostname class and replaced it with a static call. It should improve the performance.

### CODE REVIEW

**Comment by lusis** [comment]
@datenbrille can you rebase against the last merge I did? Thanks!

**Comment by datenbrille** [comment]
Hi,

I will close the pull request. JSR-353 is heavily under development. And I think I choose the wrong way to implement the feature. What is your opinion?

**Comment by lusis** [comment]
I don't have any objection to using a different JSON library. I went with the minidev one because it seemed to be the simplest and smallest. I've worked with GSON before and it was a bit more cumbersome to work with. I'm still very much a java newb so I'm leaning on the community to help point me at things that are better.

That said, If something performs better than minidev and is going to be part of a stdlib, I'd rather use it. If you feel that the JSR is a bit too volatile then maybe it makes sense to wait.

Why do you think you chose the wrong way to implement it? I didn't see any immediate problems.

**Comment by datenbrille** [comment]
Let me recode the implementation to the latest stable JSR-353 RI.

**Pull request closed without merging**
